### ISSUE TITLE
Guessing datetime fields from datetimeFormat

### ISSUE THREAD

**Issue by cjturner** [datanews/tables#10]
I have a csv file with 3 fields that all have datetime elements rigidly formatted like:
"Dec 23, 2017 12:05:36 AM" .  

According to the moment.js documentation referenced, I am providing:
   datetimeFormat: "MMM DD, YYYY HH:mm:ss a"

in the options, but all of the DTS fields get loaded (into MySQL) as varchar(48).  I have tried some variations without success.  Any suggestions?
----hours pass----
OK, I had to read the /moment.js/ docs slowly, many times...and then guess.  My data source is pretty-printing dates, with no leading zeros, and the code is enforcing _strict_, so the format has to be an array of 4 formats, allowing for single-digit months and single-digit hours, as in:
   datetimeFormat: ["MMM DD, YYYY HH:mm:ss a", "MMM DD, YYYY H:mm:ss a", "MMM D, YYYY HH:mm:ss a", "MMM D, YYYY H:mm:ss a"]

The moment.js documentation seems to infer, via certain examples, that single digit columns are implicitly supported in a two-column format, but this is not so.

**Comment by zzolo** [comment]
Hey.  It'll be a couple days before I can look at this.  But do you happen to have a sample set of data to test out with?

**Comment by cjturner** [comment]
It's sort of not your problem, I suppose, as it is just a documentation thing at moment.js.

I copied your 'pickle' code and built a test.  Here is the (working) code & test data I used to figure it out.
[guessDate.txt](https://github.com/datanews/tables/files/1585034/guessDate.txt)
