### ISSUE TITLE
Issue when configuring with Docker mysql instance.

### ISSUE THREAD

**Issue by jyotirmay123** [datanews/tables#13]
I was trying to connect to a mysql instance run by docker engine: 
docker run --name mysql_new -e MYSQL_ROOT_PASSWORD=admin -p 3306:3306 -d mysql

I am able to see the connection in mysql_workbench.

Now, I am trying to run 
tables -i server/data/some.csv --db=“mysql://root:admin@localhost/db_name” --batch-size=20

But I get below error:

TABLES
▇▇▇▇▇▇

Model guessing
▀▀▀▀▀▀▀▀▀▀▀▀▀▀
 • No models options provided, guessing data structure and types from first 1000 rows
 • Streaming: server/data/some.csv
 • Parser: csv
 • [                                                  ] 100% | 0.0s elapsed | ~0.0s left
 • Done guessing

Database
▀▀▀▀▀▀▀▀
 • Connecting to DB
/usr/local/lib/node_modules/tables/lib/tables.js:541
  if (this.dbConnectionConfg.protocol.toLowerCase().indexOf("mysql") === 0 ||
                                      ^

TypeError: Cannot read property 'toLowerCase' of null
    at Tables.dbConnect (/usr/local/lib/node_modules/tables/lib/tables.js:541:39)
    at Tables.wrapper [as dbConnect] (/usr/local/lib/node_modules/tables/node_modules/lodash/lodash.js:4941:19)
    at Tables.start (/usr/local/lib/node_modules/tables/lib/tables.js:158:8)
    at Tables.wrapper [as start] (/usr/local/lib/node_modules/tables/node_modules/lodash/lodash.js:4941:19)
    at ReadStream.streamDone (/usr/local/lib/node_modules/tables/lib/tables.js:439:18)
    at ReadStream.emit (events.js:165:20)
    at endReadableNT (_stream_readable.js:1101:12)
    at process._tickCallback (internal/process/next_tick.js:152:19)

**Comment by zzolo** [comment]
Hmmmm, the error doesn't suggest anything that is particular to Docker or your db instance at all.  I'll see if I can reproduce locally.

**Comment by zzolo** [comment]
I can't seem to recreate.  One thing I notice that might cause a problem, is that the command you sent over uses right and left double quotes, instead of just regular double quotes.  This would cause problems.

```
tables -i server/data/some.csv --db=“mysql://root:admin@localhost/db_name” --batch-size=20
```
Should be:

```
tables -i server/data/some.csv --db="mysql://root:admin@localhost/db_name" --batch-size=20
```

**Comment by jyotirmay123** [comment]
If it is working fine at your end, then probably I know the issue. Let me try that. I will let you know.

**Comment by jyotirmay123** [comment]
That was the issue with different instance of docker mysql installed in my machine.
