### ISSUE TITLE
How do I define a tab as a delimiter?

### ISSUE THREAD

**Issue by motleydev** [datanews/tables#4]
What's the syntax for defining a tab as a delimiter?

**Comment by zzolo** [comment]
Good question.  I will double check later today, but getting a tab character in there might be difficult.  A few things to try:

* `--csv-delimiter=$'\t'`
* `--csv-delimiter="\t"`
* `--csv-delimiter="	"`

**Comment by zzolo** [comment]
Just tested it out and the first option should work.  I have updated the documentation with a note for this.

`--csv-delimiter=$'\t'`
