### ISSUE TITLE
Do you have to define the headers?

### ISSUE THREAD

**Issue by motleydev** [datanews/tables#5]
Do you have to define headers or can you define "--csv-headers=true" and have the fist line infer the columns? I'm receiving errors trying that.

**Comment by zzolo** [comment]
The default is to assume headers and read them in.

If you have a sample file, I can look at, I am happy to try it out and debug further.

**Comment by motleydev** [comment]
sure, here's the file giving me issues:

https://gist.github.com/motleydev/1b1c1b65a1fdaf73842711ce27e8591a

Here's my import command:
`tables -i path/to/file.txt --db="postgres://user:pass@localhost:5432/eu_data" --csv-delimiter=$'\t' --csv-headers=true`

and this is the error:

`Error: Unexpected Error: column header mismatch expected: 1 columns got: 26`

**Comment by zzolo** [comment]
The `--csv-headers=true` option was the problem.  You don't need to set this, the default is to read the headers.  I did update the code to ignore if true is set there.  I've also created a new version, so you should be able to do a `npm install tables -g`
