### ISSUE TITLE
import csv to sqlite using code and the library

### ISSUE THREAD

**Issue by moeinrahimi** [datanews/tables#6]
hi
i want to import a csv to sqlite using library instead of terminal, but i have issue with sample code maybe it's syntax error .
```
var t = new Tables({
  input: "./looktobookstats.csv",
   {
    "modelName": {
      tableName: "table_name",
      // Fields are the same field definitions for Sequelize with a couple extra parts 
      // See: http://sequelize.readthedocs.org/en/latest/docs/models-definition/ 
      fields: {
        field1: {
          // Input field.  Used for auto-parsing 
          input: "Field 1",
          // The new name 
          name: "field1",
          // Sequelize type 
          type: new Sequelize.String(64)
        },
        field_number: {
          input: "Some Number Fld",
          name: "field_number",
          type: new Sequelize.BIGINT
        }
      },
      // Options for defining a Sequelize model 
      // See: http://sequelize.readthedocs.org/en/latest/docs/models-definition/#configuration 
      options: {
        indexes: [
          {
            fields: ["field1", "field_number"],
            unique: true
          }
        ]
      }
    },
    "anotherModel": {
      tableName: "another_table",
      
    }
});
```

**Comment by zzolo** [comment]
Can you share the data/CSV that you are working with?  Or at least a couple rows?

**Comment by moeinrahimi** [comment]
@zzolo
sure , my real problem is with syntaxes
![csvf](https://cloud.githubusercontent.com/assets/13715024/22602034/cb15af46-ea56-11e6-919f-b0a10d6a421a.png)

**Comment by moeinrahimi** [comment]
after some digging i learend  the syntax, i have a csv that it has a 'id' column(for testing)
var t = new Tables({
  input: "./123.csv",
   
    "Routes": {
      tableName: "routes",
      fields: {
        id: {
          name: "id",
          type:  Sequelize.INTEGER
        }
       
      }
    }
});

is this ok ?

my .tables.debug 
BEGIN; INSERT OR REPLACE INTO 1 (id) VALUES (?); INSERT OR REPLACE INTO 1 (id) VALUES (?); INSERT OR REPLACE INTO 1 (id) VALUES (?); INSERT OR REPLACE INTO 1 (id) VALUES (?); COMMIT

**Comment by zzolo** [comment]
This should be more like this:

```
var t = new Tables({
  input: "./123.csv",
  models: {
    "Routes": {
      tableName: "routes",
      fields: {
        id: {
          name: "id",
          type:  Sequelize.INTEGER
        }
      }
    }
  }
});
```

**Comment by moeinrahimi** [comment]
thanks !
something else how to use mysql instead of sqlite ?

**Comment by zzolo** [comment]
You can just update the `db` config options.  So, like:

```
var t = new Tables({
  input: "./123.csv",
  db: 'mysql://username:password@localhost/my-database',
  models: {
    "Routes": {
      tableName: "routes",
      fields: {
        id: {
          name: "id",
          type:  Sequelize.INTEGER
        }
      }
    }
  }
});
```
