### ISSUE TITLE
error with config file format

### ISSUE THREAD

**Issue by matt-jay** [datanews/tables#9]
I am getting the following error when trying to use a config file to define my data model:

`ERROR: Unable to read in config file with require function.`

Is there a full specification of the file format to refer to somewhere? I am really just using the "models" option, but I am not entirely sure about the expected file structure.

**Comment by zzolo** [comment]
Hey.  Sorry for the mostly unhelpful error message.

My assumption is that your JSON is not formatted perfectly.  Node's `require` function expects JSON to be exactly to the spec.  http://www.json.org/

This means all keys need to be double-quoted, and no trailing commas.

```
{
  "key": "property",
  "number": 123
}
```

If you still can't get it working, can you send along your config?
